version: "3.7"
services:
  batch_and_web_doctor:
    container_name: batch_and_web_doctor
    build:
      context: ..
      network: host
      args:
        SPRING_ACTIVE_PROFILE: batch
        BATCH_JOB_NAME: DOCTOR
        DATASOURCE_DRIVE: ${DATASOURCE_DRIVE}
        DATASOURCE_URL: ${DATASOURCE_URL}
        DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
        DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
    depends_on:
      - postgres
    networks:
      - batch-and-web-network