apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volumes-configuration
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres-app
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
        - name: postgres-container
          image: postgres:9
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "admin"
            - name: POSTGRES_DB
              value: "batch-and-web"
          volumeMounts:
            - name: volume-postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: volume-postgres-data
          persistentVolumeClaim:
            claimName: postgres-volumes-configuration
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres-app